name: Update database types

on:
    schedule:
        # sets the action to run daily at midnight
        -   cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        environment: development

        permissions:
            contents: write

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        steps:
            -   uses: actions/checkout@v4
                with:
                    persist-credentials: false
                    fetch-depth: 0

            -   uses: actions/setup-node@v2.1.5
                with:
                    node-version: 16

            -   uses: oven-sh/setup-bun@v2

            -   name: Install dependencies and generate types
                run: bunx supabase gen types --project-id "${{ secrets.PROJECT_REF}}" > modules/shared/src/types/database.types.ts

            -   name: Check for file changes
                id: git_status
                run: |
                    echo "status=$(git status -s)" >> $GITHUB_OUTPUT

            -   name: Commit files
                if: ${{ contains(steps.git_status.outputs.status, ' ') }}
                run: |
                    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git config --local user.name "github-actions[bot]"
                    git add modules/shared/src/types/database.types.ts
                    git commit -m "Update database types" -a

            -   name: Push changes
                if: ${{ contains(steps.git_status.outputs.status, ' ') }}
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: ${{ github.ref }}